AWSTemplateFormatVersion: 2010-09-09
Description: "CodePipeline artifact bucket shared by single domain (e.g. example.com)"
Parameters:
  DomainName:
    Description: "e.g. example.com"
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<![.-])
    ConstraintDescription: "Must be a valid domain name"
Resources:
  S3ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub 
        - "${tmp}-codepipeline-artifacts"
        - { tmp: !Select [0, !Split [".", !Ref DomainName]] }
      VersioningConfiguration:
        Status: Enabled
  S3ArtifactBucketPolicy:
    DependsOn: [S3ArtifactBucket]
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3ArtifactBucket
      PolicyDocument:
        Version: 2012-10-17
        Id: SSEAndSSLPolicy
        Statement:
          - 
            Sid: DenyUnEncryptedObjectUploads
            Effect: Deny
            Principal: "*"
            Action: "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${S3ArtifactBucket}/*"
            Condition:
              StringNotEquals:
                s3:x-amz-server-side-encryption: "aws:kms"
          - 
            Sid: DenyInsecureConnections
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource: !Sub "arn:aws:s3:::${S3ArtifactBucket}/*"
            Condition:
              Bool:
                aws:SecureTransport: false
Outputs:
  S3ArtifactBucketName:
    Value: !Ref S3ArtifactBucket