AWSTemplateFormatVersion: 2010-09-09
Description: Default service roles for AWS CodePipeline
Parameters:
  DomainName:
    Description: e.g. example.com
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<![.-])
    ConstraintDescription: Must be a valid domain name
Resources:
  CodePipelineDefaultTrustRole:
    Description: "Service role for AWS CodePipeline"
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Sub
        - "${tmp}-default-codepipeline-role"
        - { tmp: !Select [0, !Split [".", !Ref DomainName]] }
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [codepipeline.amazonaws.com]
          Action: sts:AssumeRole
      Path: /
  CodePipelineDefaultServicePolicy: 
    Type: "AWS::IAM::ManagedPolicy"
    Properties: 
      Description: "Policy for AWS CodePipeline Service"
      Path: "/"
      Roles: 
        - !Ref CodePipelineDefaultTrustRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - 
            Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:GetObjectVersion'
              - 's3:GetBucketVersioning'
            Resource: '*'
          - 
            Effect: Allow
            Action:
              - 's3:PutObject'
            Resource: !Sub
              - "arn:aws:s3:::${tmp}-codepipeline-artifacts*"
              - { tmp: !Select [0, !Split [".", !Ref DomainName]] }
              # - 'arn:aws:s3:::elasticbeanstalk*'
          # - 
          #   Effect: Allow
          #   Action:
          #     - 'codecommit:CancelUploadArchive'
          #     - 'codecommit:GetBranch'
          #     - 'codecommit:GetCommit'
          #     - 'codecommit:GetUploadArchiveStatus'
          #     - 'codecommit:UploadArchive'
          #   Resource: '*'
          # - 
          #   Effect: Allow
          #   Action:
          #     - 'codedeploy:CreateDeployment'
          #     - 'codedeploy:GetApplicationRevision'
          #     - 'codedeploy:GetDeployment'
          #     - 'codedeploy:GetDeploymentConfig'
          #     - 'codedeploy:RegisterApplicationRevision'
          #   Resource: '*'
          # - 
          #   Effect: Allow
          #   Action:
          #     - 'elasticbeanstalk:*'
          #     - 'ec2:*'
          #     - 'elasticloadbalancing:*'
          #     - 'autoscaling:*'
          #     - 'cloudwatch:*'
          #     - 's3:*'
          #     - 'sns:*'
          #     - 'cloudformation:*'
          #     - 'rds:*'
          #     - 'sqs:*'
          #     - 'ecs:*'
          #     - 'iam:PassRole'
          #   Resource: '*'
          # - 
          #   Effect: Allow
          #   Action:
          #     - 'lambda:InvokeFunction'
          #     - 'lambda:ListFunctions'
          #   Resource: '*'
          # - 
          #   Effect: Allow
          #   Action:
          #     - 'opsworks:CreateDeployment'
          #     - 'opsworks:DescribeApps'
          #     - 'opsworks:DescribeCommands'
          #     - 'opsworks:DescribeDeployments'
          #     - 'opsworks:DescribeInstances'
          #     - 'opsworks:DescribeStacks'
          #     - 'opsworks:UpdateApp'
          #     - 'opsworks:UpdateStack'
          #   Resource: '*'     
          - 
            Effect: Allow
            Action:
              - 'cloudformation:CreateStack'
              - 'cloudformation:DeleteStack'
              - 'cloudformation:DescribeStacks'
              - 'cloudformation:UpdateStack'
              - 'cloudformation:CreateChangeSet'
              - 'cloudformation:DeleteChangeSet'
              - 'cloudformation:DescribeChangeSet'
              - 'cloudformation:ExecuteChangeSet'
              - 'cloudformation:SetStackPolicy'
              - 'cloudformation:ValidateTemplate'
              - 'iam:PassRole'
            Resource: '*'
          - 
            Effect: Allow
            Action:
              - 'codebuild:BatchGetBuilds'
              - 'codebuild:StartBuild'
            Resource: '*'
Outputs:
  CodePipelineDefaultRoleArn:
    Value: !GetAtt CodePipelineDefaultTrustRole.Arn