AWSTemplateFormatVersion: 2010-09-09
Description: Setup the shared resources for toolings
Parameters:
  DomainName:
    Description: e.g. example.com
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<![.-])
    ConstraintDescription: Must be a valid domain name
Resources:
  S3ArtifactBucketStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DomainName: !Ref DomainName
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/toolings/pipelines/shared/artifact-bucket.yaml
  DefaultServiceRolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DomainName: !Ref DomainName
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/toolings/pipelines/shared/default-service-roles.yaml
Outputs:
  S3ArtifactBucketName:
    Value: !GetAtt S3ArtifactBucketStack.Outputs.S3ArtifactBucketName
    Export:
      Name: !Sub ${AWS::StackName}-S3ArtifactBucketName
  CodePipelineDefaultRoleArn:
    Value: !GetAtt DefaultServiceRolesStack.Outputs.CodePipelineDefaultRoleArn
    Export:
      Name: !Sub ${AWS::StackName}-CodePipelineDefaultRoleArn
  CodeBuildDefaultRoleArn:
    Value: !GetAtt DefaultServiceRolesStack.Outputs.CodeBuildDefaultRoleArn
    Export:
      Name: !Sub ${AWS::StackName}-CodeBuildDefaultRoleArn
  CloudFormationDefaultRoleArn:
    Value: !GetAtt DefaultServiceRolesStack.Outputs.CloudFormationDefaultRoleArn
    Export:
      Name: !Sub ${AWS::StackName}-CloudFormationDefaultRoleArn
  
  