AWSTemplateFormatVersion: "2010-09-09"
Description: Main for Infrastructure 
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label:
          default: General Configuration
        Parameters:
          - DomainName
          - SharedStackName
      -
        Label:
          default: CodeBuild Configuration
        Parameters:
          - Template
          - TemplateConfiguration
      -
        Label:
          default: CloudFormation Configuration
        Parameters:
          - Template
          - TemplateConfiguration
      -
        Label:
          default: GitHub Configuration
        Parameters:
          - GitHubRepoName
          - GitHubRepoBranch
          - GitHubUser
          - GitHubToken
    ParameterLabels:
      DomainName:
        default: Domain Name
      SharedStackName:
        default: Shared Stack Name
      CodeBuildImage:
        default: CodeBuild Image
      Template:
        default: Template
      TemplateConfiguration:
        default: Template Configuration
      GitHubRepoName:
        default: Repository
      GitHubRepoBranch:
        default: Branch
      GitHubUser:
        default: Username
      GitHubToken:
        default: Secret
Parameters:
  DomainName:
    Description: E.g. example.com
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<![.-])
    ConstraintDescription: Must be a valid domain name
  SharedStackName:
    Description: Shared resources for pipeline. ( Must have created the shared stack before this one. )
    Type: String
  CodeBuildImage:
    Type: String
    Default: "aws/codebuild/nodejs:7.0.0"
    Description: Image used for CodeBuild project.
  Template:
    Description: Filename for Cloudformation/SAM.
    Type: String
    Default: template.yaml
  TemplateConfiguration:
    Description: Filename for Cloudformation/SAM configuration. (  Leave empty if no config file is needed. )
    Type: String
    Default: beta.json
  GitHubRepoName:
    Type: String
  GitHubRepoBranch:
    Type: String
    Default: master
  GitHubUser:
    Type: String
  GitHubToken:
    NoEcho: true
    Type: String
Resources:
  InfrastructureServiceRolesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        DomainName: !Ref DomainName
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/toolings/pipelines/infrastructure/service-roles.yaml
  InfrastructurePipelineStack:
    Type: AWS::CloudFormation::Stack
    DependsOn: [InfrastructureServiceRolesStack]
    Properties:
      Parameters:
        DomainName: !Ref DomainName
        SharedStackName: !Ref SharedStackName
        Template: !Ref Template
        TemplateConfiguration: !Ref TemplateConfiguration
        CodeBuildImage: !Ref CodeBuildImage
        GitHubRepoName: !Ref GitHubRepoName
        GitHubRepoBranch: !Ref GitHubRepoBranch
        GitHubUser: !Ref GitHubUser
        GitHubToken: !Ref GitHubToken
        CodeBuildRoleArn: !GetAtt InfrastructureServiceRolesStack.Outputs.CodeBuildRoleArn
        # CodePipelineRoleArn: !GetAtt InfrastructureServiceRolesStack.Outputs.CodePipelineRoleArn
        CloudFormationRoleArn: !GetAtt InfrastructureServiceRolesStack.Outputs.CloudFormationRoleArn
      TemplateURL: !Sub https://s3-${AWS::Region}.amazonaws.com/toolings/pipelines/infrastructure/pipeline.yaml